#!/bin/bash

# Show battery percentage and status in i3bar.
# Change the color with the percentage and display low battery notifications.
# Clicking on the icon shows amount of time remaining/time until charged.

POWER=$(acpi -b)
if [[ "$POWER" == "" ]]; then
        exit 1
fi
STATE=$(echo $POWER | cut -d : -f 2 | cut -d , -f 1 | tr '[:upper:]' '[:lower:]' \
        | sed 's/[[:space:]]//g')
PERCENTAGE=$(echo $POWER | grep -o '[^ ]*%' | grep -o '[0-9]*')
REMAINING=$(acpi -b | cut -d % -f 2 | cut -d , -f 2)

if [[ "$STATE" == "charging" ]]; then
        COLOR="#00dd00"
        if [[ "$PERCENTAGE" -lt "10" ]]; then
                SYMBOL=""
        elif [[ "$PERCENTAGE" -lt "25" ]]; then
                SYMBOL=""
        elif [[ "$PERCENTAGE" -lt "50" ]]; then
                SYMBOL=""
        elif [[ "$PERCENTAGE" -lt "75" ]]; then
                SYMBOL=""
        elif [[ "$PERCENTAGE" -lt "95" ]]; then
                SYMBOL=""
        else
                SYMBOL=""
        fi
elif [[ "$STATE" == "discharging" ]]; then
        COLOR="#dddd00"
        if [[ "$PERCENTAGE" -lt "10" ]]; then
                SYMBOL=""
                COLOR="#dd0000"
                notify-send -t 1000 'Battery Low'
        elif [[ "$PERCENTAGE" -lt "25" ]]; then
                SYMBOL=""
                COLOR="#dd0000"
        elif [[ "$PERCENTAGE" -lt "50" ]]; then
                SYMBOL=""
        elif [[ "$PERCENTAGE" -lt "75" ]]; then
                SYMBOL=""
        elif [[ "$PERCENTAGE" -lt "95" ]]; then
                SYMBOL=""
        else
                SYMBOL=""
        fi
elif [ "$STATE" == "full" ] || [ "$STATE" == "unknown" ]; then
        SYMBOL=""
        COLOR="#00ff00"
else
        SYMBOL=""
        COLOR=""
fi

#echo $SYMBOL$PERCENTAGE%
#echo $SYMBOL$PERCENTAGE%
#echo $COLOR

echo $SYMBOL
echo $SYMBOL
echo $COLOR

if [[ $BLOCK_BUTTON == '1' ]]; then
        notify-send "Battery: $PERCENTAGE%" -t 2000
fi

if [[ $BLOCK_BUTTON == '3' ]]; then
        notify-send "$REMAINING" -t 2000
fi
