#!/bin/bash

# Create a short delay so changes in brightness can be registered
sleep 0.2

# Get the brightness percentage:
BRIGHTNESS_VALUE=$(xbacklight -get)

# Round the brightness percentage:
LC_ALL=C
BRIGHTNESS_VALUE=$(printf "%.*f" 0 $BRIGHTNESS_VALUE)

BARS_N=$(( $BRIGHTNESS_VALUE / 5 ))
SPACES_N=$((20 - BARS_N))

printf_n_times() {
 str=$1
 num=$2
 printf -v v "%-*s" "$num" ""
 echo "${v// /$str}"
}

BARS=$(printf_n_times "▮" "${BARS_N}")
SPACES=$(printf_n_times "▯" "${SPACES_N}")



# Kill previous notifications so the brightness notifications don't pile up:
killall -q dunst

# Send the notification with the icon:
notify-send "Brightness: ${BARS}${SPACES}" -t 1000
