#!/bin/bash
#echo ""$(date "+%H:%M")
echo $(date "+%D %T")
if [[ $BLOCK_BUTTON == '1' ]]; then
        firefox https://www.google.com/calendar
elif [[ $BLOCK_BUTTON == '3' ]]; then
        notify-send "$(date "+%A, %e. %B, %H:%M")" -t 1000
fi
