#!/bin/bash

sed -i ~/.config/i3/config -e 's/Material Design Icons 13/Material Design Icons 15/g'

sed -i ~/.config/i3/config -e 's/^gaps inner.*/gaps inner 40/g'
i3-msg reload
nohup python3 ~/.config/i3/scripts/autoname-workspaces.py > /dev/null &

gsettings set org.gnome.desktop.wm.preferences titlebar-font \
        'Futura Bk BT Book 14'

gsettings set org.gnome.desktop.interface font-name \
        'Futura Bk BT Book 14'

gsettings set org.gnome.desktop.interface document-font-name \
        'Futura Bk BT Book 14'

gsettings set org.gnome.desktop.interface monospace-font-name \
        'Inconsolata Medium 14'

sed -i ~/Dropbox/dotfiles/.Xdefaults -e 's/size=16/size=22/g'
sed -i ~/Dropbox/dotfiles/.Xdefaults-solarized-dark -e 's/size=16/size=22/g'
sed -i ~/Dropbox/dotfiles/.Xdefaults-solarized-light -e 's/size=16/size=22/g'
sed -i ~/Dropbox/dotfiles/.Xdefaults-tomorrow-night-eighties -e 's/size=16/size=22/g'

xrdb -load ~/Dropbox/dotfiles/.Xdefaults
