#!/bin/bash

# Show the current playing track on the mpd server.
# If the playlist is empty, display just a symbol.
# Clicking the track/symbol will open ncmpcpp.

TRACK=$(mpc -f "[[[%title% - ]%artist% - ]%album%]" | head -1)

# If the mpd server is not connected, display nothing in i3bar.
if [[ "${TRACK}" =~ "error:" ]] | [[ "${TRACK}" == "" ]] ; then
        TRACK=""
fi

# If the mpd servier is connected but nothing is in the playlist, display just
# a music symbol, which can be clicked to open ncmpcpp.
if [[ $TRACK == *volume:* ]]; then
        TRACK=""
fi

if [[ $BLOCK_BUTTON == '1' ]]; then
        WINDOW=$(pgrep ncmpc)

        if [[ "${WINDOW}" == "" ]]; then
          # use i3-msg, because otherwise doesn't always focuse
          i3-msg -q 'exec xfce4-terminal --title="ncmpc" --hold --command ncmpc'
        fi
        i3-msg -q '[title="ncmpc"] focus'
fi
if [[ $BLOCK_BUTTON == '3' ]]; then
        TITLE=$(mpc -f "[%title%]" | head -1)
        ARTIST=$(mpc -f "[%artist%]" | head -1)
        ALBUM=$(mpc -f "[%album%]" | head -1)
        notify-send "`echo -e $TITLE'\n'$ARTIST'\n'$ALBUM`"
fi

echo $TRACK | sed -e 's/?/\?/g'
