#!/bin/bash

# If WiFi is connected, show the WiFi symbol as green.
# If it's disconnected, show it as red. If dormannt, as yellow.

if ! [ -f /sys/class/net/wlp3s0/operstate ]; then
        exit 0
fi
wlan_state="$(cat /sys/class/net/wlp3s0/operstate)"

if [[ $BLOCK_BUTTON == '1' ]]; then
        gnome-control-center network
fi

if [ "$wlan_state" = "up" ]; then
        echo ""
        echo ""
        exit 0
elif [ "$wlan_state" = "down" ]; then
        echo ""
        echo ""
        echo "#DC322F"
        exit 0
elif [ "$wlan_state" = "dormant" ]; then
        echo ""
        echo ""
        echo "#F99157"
        exit 0
fi
